# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  db1:
    image: victoriametrics/victoria-metrics
    restart: always
    ports:
      - 8428:8428